/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CerezPolitikasiRouteImport } from './routes/cerez-politikasi'
import { Route as CerezlerRouteImport } from './routes/cerezler'
import { Route as EkibimizRouteImport } from './routes/ekibimiz'
import { Route as EtkinliklerRouteImport } from './routes/etkinlikler'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as GizlilikPolitikasiRouteImport } from './routes/gizlilik-politikasi'
import { Route as HaberlerRouteImport } from './routes/haberler'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as OyunlarRouteImport } from './routes/oyunlar'
import { Route as ProjelerRouteImport } from './routes/projeler'
import { Route as WpAdminLogdRouteImport } from './routes/wp-admin-logd'
import { Route as YonetimLogd2025RouteImport } from './routes/yonetim-logd-2025'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CerezPolitikasiRoute = CerezPolitikasiRouteImport.update({
  id: '/cerez-politikasi',
  path: '/cerez-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const CerezlerRoute = CerezlerRouteImport.update({
  id: '/cerezler',
  path: '/cerezler',
  getParentRoute: () => rootRouteImport,
} as any)
const EkibimizRoute = EkibimizRouteImport.update({
  id: '/ekibimiz',
  path: '/ekibimiz',
  getParentRoute: () => rootRouteImport,
} as any)
const EtkinliklerRoute = EtkinliklerRouteImport.update({
  id: '/etkinlikler',
  path: '/etkinlikler',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikPolitikasiRoute = GizlilikPolitikasiRouteImport.update({
  id: '/gizlilik-politikasi',
  path: '/gizlilik-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const HaberlerRoute = HaberlerRouteImport.update({
  id: '/haberler',
  path: '/haberler',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const OyunlarRoute = OyunlarRouteImport.update({
  id: '/oyunlar',
  path: '/oyunlar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerRoute = ProjelerRouteImport.update({
  id: '/projeler',
  path: '/projeler',
  getParentRoute: () => rootRouteImport,
} as any)
const WpAdminLogdRoute = WpAdminLogdRouteImport.update({
  id: '/wp-admin-logd',
  path: '/wp-admin-logd',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimLogd2025Route = YonetimLogd2025RouteImport.update({
  id: '/yonetim-logd-2025',
  path: '/yonetim-logd-2025',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/cerezler': typeof CerezlerRoute
  '/ekibimiz': typeof EkibimizRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/gizlilik': typeof GizlilikRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/haberler': typeof HaberlerRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/oyunlar': typeof OyunlarRoute
  '/projeler': typeof ProjelerRoute
  '/wp-admin-logd': typeof WpAdminLogdRoute
  '/yonetim-logd-2025': typeof YonetimLogd2025Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/cerezler': typeof CerezlerRoute
  '/ekibimiz': typeof EkibimizRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/gizlilik': typeof GizlilikRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/haberler': typeof HaberlerRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/oyunlar': typeof OyunlarRoute
  '/projeler': typeof ProjelerRoute
  '/wp-admin-logd': typeof WpAdminLogdRoute
  '/yonetim-logd-2025': typeof YonetimLogd2025Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/cerezler': typeof CerezlerRoute
  '/ekibimiz': typeof EkibimizRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/gizlilik': typeof GizlilikRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/haberler': typeof HaberlerRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/oyunlar': typeof OyunlarRoute
  '/projeler': typeof ProjelerRoute
  '/wp-admin-logd': typeof WpAdminLogdRoute
  '/yonetim-logd-2025': typeof YonetimLogd2025Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cerez-politikasi'
    | '/cerezler'
    | '/ekibimiz'
    | '/etkinlikler'
    | '/gizlilik'
    | '/gizlilik-politikasi'
    | '/haberler'
    | '/hakkimizda'
    | '/iletisim'
    | '/kvkk'
    | '/oyunlar'
    | '/projeler'
    | '/wp-admin-logd'
    | '/yonetim-logd-2025'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cerez-politikasi'
    | '/cerezler'
    | '/ekibimiz'
    | '/etkinlikler'
    | '/gizlilik'
    | '/gizlilik-politikasi'
    | '/haberler'
    | '/hakkimizda'
    | '/iletisim'
    | '/kvkk'
    | '/oyunlar'
    | '/projeler'
    | '/wp-admin-logd'
    | '/yonetim-logd-2025'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cerez-politikasi'
    | '/cerezler'
    | '/ekibimiz'
    | '/etkinlikler'
    | '/gizlilik'
    | '/gizlilik-politikasi'
    | '/haberler'
    | '/hakkimizda'
    | '/iletisim'
    | '/kvkk'
    | '/oyunlar'
    | '/projeler'
    | '/wp-admin-logd'
    | '/yonetim-logd-2025'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CerezPolitikasiRoute: typeof CerezPolitikasiRoute
  CerezlerRoute: typeof CerezlerRoute
  EkibimizRoute: typeof EkibimizRoute
  EtkinliklerRoute: typeof EtkinliklerRoute
  GizlilikRoute: typeof GizlilikRoute
  GizlilikPolitikasiRoute: typeof GizlilikPolitikasiRoute
  HaberlerRoute: typeof HaberlerRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  KvkkRoute: typeof KvkkRoute
  OyunlarRoute: typeof OyunlarRoute
  ProjelerRoute: typeof ProjelerRoute
  WpAdminLogdRoute: typeof WpAdminLogdRoute
  YonetimLogd2025Route: typeof YonetimLogd2025Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerez-politikasi': {
      id: '/cerez-politikasi'
      path: '/cerez-politikasi'
      fullPath: '/cerez-politikasi'
      preLoaderRoute: typeof CerezPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerezler': {
      id: '/cerezler'
      path: '/cerezler'
      fullPath: '/cerezler'
      preLoaderRoute: typeof CerezlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekibimiz': {
      id: '/ekibimiz'
      path: '/ekibimiz'
      fullPath: '/ekibimiz'
      preLoaderRoute: typeof EkibimizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etkinlikler': {
      id: '/etkinlikler'
      path: '/etkinlikler'
      fullPath: '/etkinlikler'
      preLoaderRoute: typeof EtkinliklerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik-politikasi': {
      id: '/gizlilik-politikasi'
      path: '/gizlilik-politikasi'
      fullPath: '/gizlilik-politikasi'
      preLoaderRoute: typeof GizlilikPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haberler': {
      id: '/haberler'
      path: '/haberler'
      fullPath: '/haberler'
      preLoaderRoute: typeof HaberlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyunlar': {
      id: '/oyunlar'
      path: '/oyunlar'
      fullPath: '/oyunlar'
      preLoaderRoute: typeof OyunlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler': {
      id: '/projeler'
      path: '/projeler'
      fullPath: '/projeler'
      preLoaderRoute: typeof ProjelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wp-admin-logd': {
      id: '/wp-admin-logd'
      path: '/wp-admin-logd'
      fullPath: '/wp-admin-logd'
      preLoaderRoute: typeof WpAdminLogdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim-logd-2025': {
      id: '/yonetim-logd-2025'
      path: '/yonetim-logd-2025'
      fullPath: '/yonetim-logd-2025'
      preLoaderRoute: typeof YonetimLogd2025RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CerezPolitikasiRoute: CerezPolitikasiRoute,
  CerezlerRoute: CerezlerRoute,
  EkibimizRoute: EkibimizRoute,
  EtkinliklerRoute: EtkinliklerRoute,
  GizlilikRoute: GizlilikRoute,
  GizlilikPolitikasiRoute: GizlilikPolitikasiRoute,
  HaberlerRoute: HaberlerRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  KvkkRoute: KvkkRoute,
  OyunlarRoute: OyunlarRoute,
  ProjelerRoute: ProjelerRoute,
  WpAdminLogdRoute: WpAdminLogdRoute,
  YonetimLogd2025Route: YonetimLogd2025Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
